# Request
geometry_msgs/Pose pose
float32 max_search_distance

---
# Response
int64 lane_id
int32 lane_index
int32 lane_count
float32 speed_limit
bool has_left_neighbor
bool has_right_neighbor
bool in_intersection
