use_sim_time: true
carla:
  # the network connection for the python connection to CARLA, can be overwritten by launch parameters
  # don't make anything other than the host setting reference an environment variable
  host: $(optenv CARLA_HOSTNAME localhost)
  port: 2000
  timeout: 20
  # enable/disable synchronous mode. If enabled ros-bridge waits until
  # expected data is received for all sensors
  synchronous_mode: true
  # within synchronous mode: wait for a vehicle control command before next tick?
  synchronous_mode_wait_for_vehicle_control_command: false
  # set the fixed timestep length
  fixed_delta_seconds: 0.05
  # town
  # options:
  # Town05, mcity
  town: Town10HD_Opt
  # configuration values for the ego vehicle
  ego_vehicle:
    # the role name of the vehicles that acts as ego vehicle for this ros bridge instance
    # Only the vehicles within this list are controllable from within ROS.
    # (the vehicle from CARLA is selected which has the attribute 'role_name' set to this value)
    role_name: ego
  ackermann_control:
    # override the default values of the pid speed controller
    # (only relevant for ackermann control mode) 
    control_loop_rate: 0.05