bbox_2d_3d:
  ros__parameters:
    # subscribers

    camera_info_topic_front_: /CAM_FRONT/camera_info
    camera_info_topic_right_: /CAM_FRONT_RIGHT/camera_info
    camera_info_topic_left_: /CAM_FRONT_LEFT/camera_info

    lidar_topic: /LIDAR_TOP
    detections_topic: /batched_camera_message

    # publishers
    filtered_lidar_topic: /filtered_lidar
    cluster_centroid_topic: /cluster_centroid
    bounding_box_topic: /bounding_box
    detection_3d_topic: /detection_3d
    # lidar frames
    lidar_top_frame: LIDAR_TOP

    #camera detections
    cam_front_detections: /CAM_FRONT/detections
    cam_front_right_detections: /CAM_FRONT_RIGHT/detections
    cam_front_left_detections: /CAM_FRONT_LEFT/detections

    # filtering parameters
    ransac_params:
      distance_threshold: 0.5
      # maximum allowed distance a point can be from the estimated plane to still be considered an inlier
      max_iterations: 1500
      # the number of times ransac randomly samples a point to estimate a plane, higher number means more accurate plane estimation but heavier computation

    euclid_params:
      cluster_tolerance: 0.5
      #This defines the maximum distance between two points for them to be considered part of the same cluster
      min_cluster_size: 50 # small values create more noise 
      max_cluster_size: 700 # big values slightly slow down performance

    # 2d/3d IOU matching params
    matching_params:
      object_detection_confidence: 0.45
      iou_threshold: 0.4

    publish_visualization: true

      