---
services:
  world_modeling_bringup:
    build:
      context: ..
      dockerfile: docker/world_modeling/world_modeling.Dockerfile
      cache_from:
        - "${WORLD_MODELING_IMAGE}:build_${TAG}"
        - "${WORLD_MODELING_IMAGE}:build_main"
      target: deploy
    image: "${WORLD_MODELING_IMAGE}:${TAG}"
    command: /bin/bash -c "ros2 launch world_modeling_bringup world_modeling_launch.yaml"
