version: "3.8"
services:
  cpp_aggregator: # C++
    build:
      context: ..
      dockerfile: docker/samples/cpp_aggregator/cpp_aggregator.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:main"
    image: "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
    security_opt:
      - seccomp:${MONO_DIR}/modules/seccomp_profile.json 
    command: /bin/bash -c "ros2 launch aggregator aggregator.launch.py"

  # py_aggregator: # PYTHON
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/py_aggregator/py_aggregator.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:main"
  #   image: "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:${TAG}"
  #   security_opt:
  #     - seccomp:${MONO_DIR}/modules/seccomp_profile.json 
  #   command: /bin/bash -c "ros2 launch aggregator aggregator.launch.py"

  # cpp_producer: # C++
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/cpp_producer/cpp_producer.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:main"
  #   image: "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
  #   security_opt:
  #     - seccomp:${MONO_DIR}/modules/seccomp_profile.json 
  #   command: /bin/bash -c "ros2 launch producer producer.launch.py"

  py_producer: # PYTHON
    build:
      context: ..
      dockerfile: docker/samples/py_producer/py_producer.Dockerfile
      cache_from:
        - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:${TAG}"
        - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:main"
    image: "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:${TAG}"
    security_opt:
      - seccomp:${MONO_DIR}/modules/seccomp_profile.json 
    command: /bin/bash -c "ros2 launch producer producer.launch.py"

  # cpp_transformer: # C++
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/cpp_transformer/cpp_transformer.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:main"
  #   image: "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
  #   security_opt:
  #     - seccomp:${MONO_DIR}/modules/seccomp_profile.json 
  #   command: /bin/bash -c "ros2 launch transformer transformer.launch.py"

  py_transformer: # PYTHON
    build:
      context: ..
      dockerfile: docker/samples/py_transformer/py_transformer.Dockerfile
      cache_from:
        - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:${TAG}"
        - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:main"
    image: "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:${TAG}"
    security_opt:
      - seccomp:${MONO_DIR}/modules/seccomp_profile.json 
    command: /bin/bash -c "ros2 launch transformer transformer.launch.py"
