#  __          __  _______
#  \ \        / /\|__   __|
#   \ \  /\  / /  \  | | ___  _ __   ___  _ __ ___   ___  _   _ ___
#    \ \/  \/ / /\ \ | |/ _ \| '_ \ / _ \| '_ ` _ \ / _ \| | | / __|
#     \  /\  / ____ \| | (_) | | | | (_) | | | | | | (_) | |_| \__ \
#      \/  \/_/    \_\_|\___/|_| |_|\___/|_| |_| |_|\___/ \__,_|___/
# 
# WATO CONFIG: 
# Central configuration file to specify what autonomous vehicle profiles to run. Set any of the 
# profiles to True run them with watod2.
#
# Note: You can run all profiles using watod2 -a

# Samples
samples_cpp: True

# Infrastructure
vis_tools: False
data_stream: False

# Perception

# World Modeling 

# Motion Planning and Control

# Simulation