name: Check source file changes

outputs:
  modified_modules:
    description: "Space deliminated list of modified modules"
    value: ${{ steps.output-changes.outputs.modified_modules }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Find changed files inside action folder
      id: changed-files-action
      uses: tj-actions/changed-files@v42
      with:
        files: src/action/**
      
    - name: Get changed files inside interfacing folder
      id: changed-files-interfacing
      uses: tj-actions/changed-files@v42
      with:
        files: src/interfacing/**
    
    - name: Get changed files inside perception folder
      id: changed-files-perception
      uses: tj-actions/changed-files@v42
      with:
        files: src/perception/**
    
    - name: Get changed files inside samples folder
      id: changed-files-samples
      uses: tj-actions/changed-files@v42
      with:
        files: src/samples/**
    
    - name: Get changed files inside simulation folder
      id: changed-files-simulation
      uses: tj-actions/changed-files@v42
      with:
        files: src/simulation/**
    
    - name: Get changed files inside world_modeling folder
      id: changed-files-world-modeling
      uses: tj-actions/changed-files@v42
      with:
        files: src/world_modeling/**

    - name: Create list of changed modules
      id: output-changes
      env:
        ACTION_CHANGED: ${{ steps.changed-files-action.outputs.any_changed }}
        INTERFACING_CHANGED: ${{ steps.changed-files-interfacing.outputs.any_changed }}
        PERCEPTION_CHANGED: ${{ steps.changed-files-perception.outputs.any_changed }}
        SAMPLES_CHANGED: ${{ steps.changed-files-samples.outputs.any_changed }}
        SIMULATION_CHANGED: ${{ steps.changed-files-simulation.outputs.any_changed }}
        WORLD_MODELING_CHANGED: ${{ steps.changed-files-world-modeling.outputs.any_changed }}

      run: ${{ github.action_path }}/check_src_changes.sh
      shell: bash
    
    - name: Sanity check
      run: echo "sus ${{ steps.output-changes.outputs.modified_modules }}"
      shell: bash