shape_range_info {
  name: "batch_norm2d_0.b_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_0.w_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_0.w_1"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_0.w_2"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_1.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_1.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_1.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_1.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_10.b_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_10.w_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_10.w_1"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_10.w_2"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_11.b_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_11.w_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_11.w_1"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_11.w_2"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_12.b_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_12.w_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_12.w_1"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_12.w_2"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_13.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_13.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_13.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_13.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_14.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_14.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_14.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_14.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_15.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_15.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_15.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_15.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_16.b_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_16.w_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_16.w_1"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_16.w_2"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_17.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_17.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_17.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_17.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_18.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_18.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_18.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_18.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_19.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_19.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_19.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_19.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_2.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_2.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_2.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_2.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_20.b_0"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_20.w_0"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_20.w_1"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_20.w_2"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_21.b_0"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_21.w_0"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_21.w_1"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_21.w_2"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_22.b_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_22.w_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_22.w_1"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_22.w_2"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_23.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_23.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_23.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_23.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_24.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_24.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_24.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_24.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_25.b_0"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_25.w_0"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_25.w_1"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_25.w_2"
  min_shape: 512
  max_shape: 512
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm2d_26.b_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_26.w_0"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_26.w_1"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_26.w_2"
  min_shape: 256
  max_shape: 256
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm2d_27.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_27.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_27.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_27.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_28.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_28.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_28.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_28.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_29.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_29.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_29.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_29.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_3.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_3.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_3.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_3.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_30.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_30.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_30.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_30.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_31.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_31.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_31.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_31.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_32.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_32.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_32.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_32.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_33.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_33.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_33.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_33.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_34.b_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_34.w_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_34.w_1"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_34.w_2"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_35.b_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_35.w_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_35.w_1"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_35.w_2"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_36.b_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_36.w_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_36.w_1"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_36.w_2"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_37.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_37.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_37.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_37.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_38.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_38.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_38.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_38.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_39.b_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_39.w_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_39.w_1"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_39.w_2"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_4.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_4.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_4.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_4.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_40.b_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_40.w_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_40.w_1"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_40.w_2"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_41.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_41.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_41.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_41.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_42.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_42.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_42.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_42.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_43.b_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_43.w_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_43.w_1"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_43.w_2"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm2d_44.b_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_44.w_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_44.w_1"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_44.w_2"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm2d_45.b_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_45.w_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_45.w_1"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_45.w_2"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_5.b_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_5.w_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_5.w_1"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_5.w_2"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_6.b_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_6.w_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_6.w_1"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_6.w_2"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_7.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_7.w_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_7.w_1"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_7.w_2"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm2d_8.b_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_8.w_0"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_8.w_1"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_8.w_2"
  min_shape: 64
  max_shape: 64
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm2d_9.b_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_9.w_0"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_9.w_1"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm2d_9.w_2"
  min_shape: 32
  max_shape: 32
  opt_shape: 32
}
shape_range_info {
  name: "batch_norm_0.tmp_2"
  min_shape: 1
  min_shape: 32
  min_shape: 512
  min_shape: 1024
  max_shape: 1
  max_shape: 32
  max_shape: 512
  max_shape: 1024
  opt_shape: 1
  opt_shape: 32
  opt_shape: 512
  opt_shape: 1024
}
shape_range_info {
  name: "batch_norm_1.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 256
  min_shape: 512
  max_shape: 1
  max_shape: 64
  max_shape: 256
  max_shape: 512
  opt_shape: 1
  opt_shape: 64
  opt_shape: 256
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm_10.tmp_2"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_11.tmp_2"
  min_shape: 1
  min_shape: 256
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 256
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 256
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_12.tmp_2"
  min_shape: 1
  min_shape: 256
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 256
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 256
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_13.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_14.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_15.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_16.tmp_2"
  min_shape: 1
  min_shape: 256
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 256
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 256
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_17.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_18.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_19.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_2.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 256
  min_shape: 512
  max_shape: 1
  max_shape: 128
  max_shape: 256
  max_shape: 512
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
  opt_shape: 512
}
shape_range_info {
  name: "batch_norm_20.tmp_2"
  min_shape: 1
  min_shape: 512
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 512
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 512
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_21.tmp_2"
  min_shape: 1
  min_shape: 512
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 512
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 512
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_22.tmp_2"
  min_shape: 1
  min_shape: 256
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 256
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 256
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_23.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_24.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_25.tmp_2"
  min_shape: 1
  min_shape: 512
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 512
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 512
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_26.tmp_2"
  min_shape: 1
  min_shape: 256
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 256
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 256
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_27.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_28.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_29.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 1
  min_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 1
  max_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "batch_norm_3.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 128
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 128
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_30.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 2
  min_shape: 2
  max_shape: 1
  max_shape: 128
  max_shape: 2
  max_shape: 2
  opt_shape: 1
  opt_shape: 128
  opt_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "batch_norm_31.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 4
  min_shape: 4
  max_shape: 1
  max_shape: 128
  max_shape: 4
  max_shape: 4
  opt_shape: 1
  opt_shape: 128
  opt_shape: 4
  opt_shape: 4
}
shape_range_info {
  name: "batch_norm_32.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_33.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_34.tmp_2"
  min_shape: 1
  min_shape: 2
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 2
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 2
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_35.tmp_2"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_36.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "batch_norm_37.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_38.tmp_2"
  min_shape: 1
  min_shape: 2
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 2
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 2
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_39.tmp_2"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_4.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_40.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "batch_norm_41.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_42.tmp_2"
  min_shape: 1
  min_shape: 2
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 2
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 2
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_43.tmp_2"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_44.tmp_2"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_45.tmp_2"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_5.tmp_2"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_6.tmp_2"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_7.tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 128
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 128
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_8.tmp_2"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "batch_norm_9.tmp_2"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "bilinear_interp_v2_0.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "bilinear_interp_v2_1.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "bilinear_interp_v2_2.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "bilinear_interp_v2_3.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "bilinear_interp_v2_4.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "bilinear_interp_v2_5.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "bilinear_interp_v2_6.tmp_0"
  min_shape: 1
  min_shape: 19
  min_shape: 1024
  min_shape: 2048
  max_shape: 1
  max_shape: 19
  max_shape: 1024
  max_shape: 2048
  opt_shape: 1
  opt_shape: 19
  opt_shape: 1024
  opt_shape: 2048
}
shape_range_info {
  name: "concat_0.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 256
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 256
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "concat_1.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 256
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 256
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "concat_2.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 512
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 512
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "concat_3.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 512
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 512
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "concat_4.tmp_0"
  min_shape: 1
  min_shape: 1024
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1024
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1024
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "concat_5.tmp_0"
  min_shape: 1
  min_shape: 1024
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1024
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1024
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "concat_6.tmp_0"
  min_shape: 1
  min_shape: 4
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 4
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 4
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "concat_7.tmp_0"
  min_shape: 1
  min_shape: 4
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 4
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 4
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "concat_8.tmp_0"
  min_shape: 1
  min_shape: 4
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 4
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 4
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_0.w_0"
  min_shape: 32
  min_shape: 3
  min_shape: 3
  min_shape: 3
  max_shape: 32
  max_shape: 3
  max_shape: 3
  max_shape: 3
  opt_shape: 32
  opt_shape: 3
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_1.w_0"
  min_shape: 64
  min_shape: 32
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 32
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 32
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_10.w_0"
  min_shape: 32
  min_shape: 32
  min_shape: 3
  min_shape: 3
  max_shape: 32
  max_shape: 32
  max_shape: 3
  max_shape: 3
  opt_shape: 32
  opt_shape: 32
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_11.w_0"
  min_shape: 256
  min_shape: 1
  min_shape: 3
  min_shape: 3
  max_shape: 256
  max_shape: 1
  max_shape: 3
  max_shape: 3
  opt_shape: 256
  opt_shape: 1
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_12.w_0"
  min_shape: 256
  min_shape: 256
  min_shape: 1
  min_shape: 1
  max_shape: 256
  max_shape: 256
  max_shape: 1
  max_shape: 1
  opt_shape: 256
  opt_shape: 256
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_13.w_0"
  min_shape: 128
  min_shape: 256
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 256
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 256
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_14.w_0"
  min_shape: 64
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_15.w_0"
  min_shape: 64
  min_shape: 64
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 64
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 64
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_16.w_0"
  min_shape: 256
  min_shape: 512
  min_shape: 1
  min_shape: 1
  max_shape: 256
  max_shape: 512
  max_shape: 1
  max_shape: 1
  opt_shape: 256
  opt_shape: 512
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_17.w_0"
  min_shape: 128
  min_shape: 256
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 256
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 256
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_18.w_0"
  min_shape: 64
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_19.w_0"
  min_shape: 64
  min_shape: 64
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 64
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 64
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_2.w_0"
  min_shape: 128
  min_shape: 1
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 1
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 1
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_20.w_0"
  min_shape: 512
  min_shape: 1
  min_shape: 3
  min_shape: 3
  max_shape: 512
  max_shape: 1
  max_shape: 3
  max_shape: 3
  opt_shape: 512
  opt_shape: 1
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_21.w_0"
  min_shape: 512
  min_shape: 512
  min_shape: 1
  min_shape: 1
  max_shape: 512
  max_shape: 512
  max_shape: 1
  max_shape: 1
  opt_shape: 512
  opt_shape: 512
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_22.w_0"
  min_shape: 256
  min_shape: 512
  min_shape: 3
  min_shape: 3
  max_shape: 256
  max_shape: 512
  max_shape: 3
  max_shape: 3
  opt_shape: 256
  opt_shape: 512
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_23.w_0"
  min_shape: 128
  min_shape: 256
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 256
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 256
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_24.w_0"
  min_shape: 128
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_25.w_0"
  min_shape: 512
  min_shape: 1024
  min_shape: 1
  min_shape: 1
  max_shape: 512
  max_shape: 1024
  max_shape: 1
  max_shape: 1
  opt_shape: 512
  opt_shape: 1024
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_26.w_0"
  min_shape: 256
  min_shape: 512
  min_shape: 3
  min_shape: 3
  max_shape: 256
  max_shape: 512
  max_shape: 3
  max_shape: 3
  opt_shape: 256
  opt_shape: 512
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_27.w_0"
  min_shape: 128
  min_shape: 256
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 256
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 256
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_28.w_0"
  min_shape: 128
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_29.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_29.w_0"
  min_shape: 128
  min_shape: 1024
  min_shape: 1
  min_shape: 1
  max_shape: 128
  max_shape: 1024
  max_shape: 1
  max_shape: 1
  opt_shape: 128
  opt_shape: 1024
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_3.w_0"
  min_shape: 128
  min_shape: 64
  min_shape: 1
  min_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 1
  max_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_30.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_30.w_0"
  min_shape: 128
  min_shape: 1024
  min_shape: 1
  min_shape: 1
  max_shape: 128
  max_shape: 1024
  max_shape: 1
  max_shape: 1
  opt_shape: 128
  opt_shape: 1024
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_31.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_31.w_0"
  min_shape: 128
  min_shape: 1024
  min_shape: 1
  min_shape: 1
  max_shape: 128
  max_shape: 1024
  max_shape: 1
  max_shape: 1
  opt_shape: 128
  opt_shape: 1024
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_32.b_0"
  min_shape: 128
  max_shape: 128
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_32.w_0"
  min_shape: 128
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_33.w_0"
  min_shape: 64
  min_shape: 256
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 256
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 256
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_34.w_0"
  min_shape: 32
  min_shape: 64
  min_shape: 3
  min_shape: 3
  max_shape: 32
  max_shape: 64
  max_shape: 3
  max_shape: 3
  opt_shape: 32
  opt_shape: 64
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_35.w_0"
  min_shape: 2
  min_shape: 4
  min_shape: 3
  min_shape: 3
  max_shape: 2
  max_shape: 4
  max_shape: 3
  max_shape: 3
  opt_shape: 2
  opt_shape: 4
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_36.w_0"
  min_shape: 1
  min_shape: 2
  min_shape: 3
  min_shape: 3
  max_shape: 1
  max_shape: 2
  max_shape: 3
  max_shape: 3
  opt_shape: 1
  opt_shape: 2
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_37.w_0"
  min_shape: 128
  min_shape: 512
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 512
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 512
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_38.w_0"
  min_shape: 64
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_39.w_0"
  min_shape: 2
  min_shape: 4
  min_shape: 3
  min_shape: 3
  max_shape: 2
  max_shape: 4
  max_shape: 3
  max_shape: 3
  opt_shape: 2
  opt_shape: 4
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_4.w_0"
  min_shape: 64
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_40.w_0"
  min_shape: 1
  min_shape: 2
  min_shape: 3
  min_shape: 3
  max_shape: 1
  max_shape: 2
  max_shape: 3
  max_shape: 3
  opt_shape: 1
  opt_shape: 2
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_41.w_0"
  min_shape: 128
  min_shape: 1024
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 1024
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 1024
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_42.w_0"
  min_shape: 128
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 128
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 128
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_43.w_0"
  min_shape: 2
  min_shape: 4
  min_shape: 3
  min_shape: 3
  max_shape: 2
  max_shape: 4
  max_shape: 3
  max_shape: 3
  opt_shape: 2
  opt_shape: 4
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_44.w_0"
  min_shape: 1
  min_shape: 2
  min_shape: 3
  min_shape: 3
  max_shape: 1
  max_shape: 2
  max_shape: 3
  max_shape: 3
  opt_shape: 1
  opt_shape: 2
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_45.w_0"
  min_shape: 32
  min_shape: 32
  min_shape: 3
  min_shape: 3
  max_shape: 32
  max_shape: 32
  max_shape: 3
  max_shape: 3
  opt_shape: 32
  opt_shape: 32
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_46.w_0"
  min_shape: 19
  min_shape: 32
  min_shape: 1
  min_shape: 1
  max_shape: 19
  max_shape: 32
  max_shape: 1
  max_shape: 1
  opt_shape: 19
  opt_shape: 32
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_5.w_0"
  min_shape: 32
  min_shape: 64
  min_shape: 3
  min_shape: 3
  max_shape: 32
  max_shape: 64
  max_shape: 3
  max_shape: 3
  opt_shape: 32
  opt_shape: 64
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_51.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 512
  min_shape: 1024
  max_shape: 1
  max_shape: 32
  max_shape: 512
  max_shape: 1024
  opt_shape: 1
  opt_shape: 32
  opt_shape: 512
  opt_shape: 1024
}
shape_range_info {
  name: "conv2d_52.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 256
  min_shape: 512
  max_shape: 1
  max_shape: 64
  max_shape: 256
  max_shape: 512
  opt_shape: 1
  opt_shape: 64
  opt_shape: 256
  opt_shape: 512
}
shape_range_info {
  name: "conv2d_53.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 256
  min_shape: 512
  max_shape: 1
  max_shape: 128
  max_shape: 256
  max_shape: 512
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
  opt_shape: 512
}
shape_range_info {
  name: "conv2d_54.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_55.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_56.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_57.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 128
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 128
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_58.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_59.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_6.w_0"
  min_shape: 32
  min_shape: 32
  min_shape: 3
  min_shape: 3
  max_shape: 32
  max_shape: 32
  max_shape: 3
  max_shape: 3
  opt_shape: 32
  opt_shape: 32
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_60.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_61.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 256
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 256
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_62.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_63.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_64.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_65.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 256
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 256
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_66.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_67.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_68.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_69.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 512
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 512
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_7.w_0"
  min_shape: 128
  min_shape: 256
  min_shape: 1
  min_shape: 1
  max_shape: 128
  max_shape: 256
  max_shape: 1
  max_shape: 1
  opt_shape: 128
  opt_shape: 256
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_70.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 256
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 256
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_71.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_72.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_73.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 512
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 512
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_74.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 256
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 256
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_75.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_76.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_77.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 1
  min_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 1
  max_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_77.tmp_1"
  min_shape: 1
  min_shape: 128
  min_shape: 1
  min_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 1
  max_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "conv2d_78.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 2
  min_shape: 2
  max_shape: 1
  max_shape: 128
  max_shape: 2
  max_shape: 2
  opt_shape: 1
  opt_shape: 128
  opt_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "conv2d_78.tmp_1"
  min_shape: 1
  min_shape: 128
  min_shape: 2
  min_shape: 2
  max_shape: 1
  max_shape: 128
  max_shape: 2
  max_shape: 2
  opt_shape: 1
  opt_shape: 128
  opt_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "conv2d_79.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 4
  min_shape: 4
  max_shape: 1
  max_shape: 128
  max_shape: 4
  max_shape: 4
  opt_shape: 1
  opt_shape: 128
  opt_shape: 4
  opt_shape: 4
}
shape_range_info {
  name: "conv2d_79.tmp_1"
  min_shape: 1
  min_shape: 128
  min_shape: 4
  min_shape: 4
  max_shape: 1
  max_shape: 128
  max_shape: 4
  max_shape: 4
  opt_shape: 1
  opt_shape: 128
  opt_shape: 4
  opt_shape: 4
}
shape_range_info {
  name: "conv2d_8.w_0"
  min_shape: 64
  min_shape: 128
  min_shape: 3
  min_shape: 3
  max_shape: 64
  max_shape: 128
  max_shape: 3
  max_shape: 3
  opt_shape: 64
  opt_shape: 128
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_80.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_80.tmp_1"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_81.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_82.tmp_0"
  min_shape: 1
  min_shape: 2
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 2
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 2
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_83.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_84.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "conv2d_85.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_86.tmp_0"
  min_shape: 1
  min_shape: 2
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 2
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 2
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_87.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_88.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "conv2d_89.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_9.w_0"
  min_shape: 32
  min_shape: 64
  min_shape: 3
  min_shape: 3
  max_shape: 32
  max_shape: 64
  max_shape: 3
  max_shape: 3
  opt_shape: 32
  opt_shape: 64
  opt_shape: 3
  opt_shape: 3
}
shape_range_info {
  name: "conv2d_90.tmp_0"
  min_shape: 1
  min_shape: 2
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 2
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 2
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_91.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_92.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_93.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "conv2d_94.tmp_0"
  min_shape: 1
  min_shape: 19
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 19
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 19
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "depthwise_conv2d_0.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 128
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 128
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "depthwise_conv2d_1.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 256
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 256
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "depthwise_conv2d_2.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 512
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 512
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "max_0.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "max_1.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "max_2.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "max_3.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "max_4.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "max_5.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "mean_0.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "mean_1.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "mean_2.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "mean_3.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "mean_4.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "mean_5.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "pool2d_0.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 128
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 128
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "pool2d_1.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 256
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 256
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "pool2d_2.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 512
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 512
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "pool2d_3.tmp_0"
  min_shape: 1
  min_shape: 1024
  min_shape: 1
  min_shape: 1
  max_shape: 1
  max_shape: 1024
  max_shape: 1
  max_shape: 1
  opt_shape: 1
  opt_shape: 1024
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "pool2d_4.tmp_0"
  min_shape: 1
  min_shape: 1024
  min_shape: 2
  min_shape: 2
  max_shape: 1
  max_shape: 1024
  max_shape: 2
  max_shape: 2
  opt_shape: 1
  opt_shape: 1024
  opt_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "pool2d_5.tmp_0"
  min_shape: 1
  min_shape: 1024
  min_shape: 4
  min_shape: 4
  max_shape: 1
  max_shape: 1024
  max_shape: 4
  max_shape: 4
  opt_shape: 1
  opt_shape: 1024
  opt_shape: 4
  opt_shape: 4
}
shape_range_info {
  name: "relu_0.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 512
  min_shape: 1024
  max_shape: 1
  max_shape: 32
  max_shape: 512
  max_shape: 1024
  opt_shape: 1
  opt_shape: 32
  opt_shape: 512
  opt_shape: 1024
}
shape_range_info {
  name: "relu_1.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 256
  min_shape: 512
  max_shape: 1
  max_shape: 64
  max_shape: 256
  max_shape: 512
  opt_shape: 1
  opt_shape: 64
  opt_shape: 256
  opt_shape: 512
}
shape_range_info {
  name: "relu_10.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 256
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 256
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_11.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_12.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_13.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_14.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 256
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 256
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_15.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_16.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_17.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_18.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 512
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 512
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_19.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 256
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 256
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_2.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 256
  min_shape: 512
  max_shape: 1
  max_shape: 128
  max_shape: 256
  max_shape: 512
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
  opt_shape: 512
}
shape_range_info {
  name: "relu_20.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_21.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_22.tmp_0"
  min_shape: 1
  min_shape: 512
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 512
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 512
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_23.tmp_0"
  min_shape: 1
  min_shape: 256
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 256
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 256
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_24.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_25.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_26.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 1
  min_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 1
  max_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "relu_27.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 2
  min_shape: 2
  max_shape: 1
  max_shape: 128
  max_shape: 2
  max_shape: 2
  opt_shape: 1
  opt_shape: 128
  opt_shape: 2
  opt_shape: 2
}
shape_range_info {
  name: "relu_28.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 4
  min_shape: 4
  max_shape: 1
  max_shape: 128
  max_shape: 4
  max_shape: 4
  opt_shape: 1
  opt_shape: 128
  opt_shape: 4
  opt_shape: 4
}
shape_range_info {
  name: "relu_29.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_3.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_30.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_31.tmp_0"
  min_shape: 1
  min_shape: 2
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 2
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 2
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_32.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "relu_33.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_34.tmp_0"
  min_shape: 1
  min_shape: 2
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 2
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 2
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_35.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 64
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 64
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "relu_36.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_37.tmp_0"
  min_shape: 1
  min_shape: 2
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 2
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 2
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_38.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_39.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_4.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_5.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_6.tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 128
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 128
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_7.tmp_0"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_8.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "relu_9.tmp_0"
  min_shape: 1
  min_shape: 32
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 32
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 32
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "shape_0.tmp_0"
  min_shape: 4
  max_shape: 4
  opt_shape: 4
  min_value: 1
  min_value: 3
  min_value: 1024
  min_value: 2048
  max_value: 1
  max_value: 3
  max_value: 1024
  max_value: 2048
  opt_value: 1
  opt_value: 3
  opt_value: 1024
  opt_value: 2048
}
shape_range_info {
  name: "shape_0.tmp_0_slice_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
  min_value: 1024
  min_value: 2048
  max_value: 1024
  max_value: 2048
  opt_value: 1024
  opt_value: 2048
}
shape_range_info {
  name: "shape_1.tmp_0"
  min_shape: 4
  max_shape: 4
  opt_shape: 4
  min_value: 1
  min_value: 1024
  min_value: 32
  min_value: 64
  max_value: 1
  max_value: 1024
  max_value: 32
  max_value: 64
  opt_value: 1
  opt_value: 1024
  opt_value: 32
  opt_value: 64
}
shape_range_info {
  name: "shape_1.tmp_0_slice_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
  min_value: 32
  min_value: 64
  max_value: 32
  max_value: 64
  opt_value: 32
  opt_value: 64
}
shape_range_info {
  name: "shape_2.tmp_0"
  min_shape: 4
  max_shape: 4
  opt_shape: 4
  min_value: 1
  min_value: 128
  min_value: 32
  min_value: 64
  max_value: 1
  max_value: 128
  max_value: 32
  max_value: 64
  opt_value: 1
  opt_value: 128
  opt_value: 32
  opt_value: 64
}
shape_range_info {
  name: "shape_2.tmp_0_slice_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
  min_value: 32
  min_value: 64
  max_value: 32
  max_value: 64
  opt_value: 32
  opt_value: 64
}
shape_range_info {
  name: "shape_3.tmp_0"
  min_shape: 4
  max_shape: 4
  opt_shape: 4
  min_value: 1
  min_value: 128
  min_value: 64
  min_value: 128
  max_value: 1
  max_value: 128
  max_value: 64
  max_value: 128
  opt_value: 1
  opt_value: 128
  opt_value: 64
  opt_value: 128
}
shape_range_info {
  name: "shape_3.tmp_0_slice_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
  min_value: 64
  min_value: 128
  max_value: 64
  max_value: 128
  opt_value: 64
  opt_value: 128
}
shape_range_info {
  name: "shape_4.tmp_0"
  min_shape: 4
  max_shape: 4
  opt_shape: 4
  min_value: 1
  min_value: 64
  min_value: 128
  min_value: 256
  max_value: 1
  max_value: 64
  max_value: 128
  max_value: 256
  opt_value: 1
  opt_value: 64
  opt_value: 128
  opt_value: 256
}
shape_range_info {
  name: "shape_4.tmp_0_slice_0"
  min_shape: 2
  max_shape: 2
  opt_shape: 2
  min_value: 128
  min_value: 256
  max_value: 128
  max_value: 256
  opt_value: 128
  opt_value: 256
}
shape_range_info {
  name: "sigmoid_0.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "sigmoid_1.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "sigmoid_2.tmp_0"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "tmp_0"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "tmp_1"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "tmp_10"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "tmp_11"
  min_shape: 1
  min_shape: 1
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 1
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 1
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "tmp_12"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "tmp_13"
  min_shape: 1
  min_shape: 64
  min_shape: 128
  min_shape: 256
  max_shape: 1
  max_shape: 64
  max_shape: 128
  max_shape: 256
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
  opt_shape: 256
}
shape_range_info {
  name: "tmp_2"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "tmp_3"
  min_shape: 1
  min_shape: 1
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 1
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 1
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "tmp_4"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "tmp_5"
  min_shape: 1
  min_shape: 128
  min_shape: 32
  min_shape: 64
  max_shape: 1
  max_shape: 128
  max_shape: 32
  max_shape: 64
  opt_shape: 1
  opt_shape: 128
  opt_shape: 32
  opt_shape: 64
}
shape_range_info {
  name: "tmp_6"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "tmp_7"
  min_shape: 1
  min_shape: 1
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 1
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 1
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "tmp_8"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "tmp_9"
  min_shape: 1
  min_shape: 128
  min_shape: 64
  min_shape: 128
  max_shape: 1
  max_shape: 128
  max_shape: 64
  max_shape: 128
  opt_shape: 1
  opt_shape: 128
  opt_shape: 64
  opt_shape: 128
}
shape_range_info {
  name: "uafm__sp_atten_0.w_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "uafm__sp_atten_1.w_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "uafm__sp_atten_2.w_0"
  min_shape: 1
  max_shape: 1
  opt_shape: 1
}
shape_range_info {
  name: "x"
  min_shape: 1
  min_shape: 3
  min_shape: 1024
  min_shape: 2048
  max_shape: 1
  max_shape: 3
  max_shape: 1024
  max_shape: 2048
  opt_shape: 1
  opt_shape: 3
  opt_shape: 1024
  opt_shape: 2048
}
