name: Generate GitHub Environment

outputs:
  source_branch:
    description: "branch we are currently on"
    value: ${{ steps.environment-generator.outputs.source_branch }}
  target_branch:
    description: "branch we are trying to merge into"
    value: ${{ steps.environment-generator.outputs.target_branch }}

runs:
  using: "composite"
  steps:
    - id: environment-generator
      run: ${{ github.action_path }}/github_context.sh
      shell: bash