camera_object_detection_node:
  ros__parameters:
    camera_topic: /camera_pkg/display_mjpeg
    publish_vis_topic: /annotated_img
    publish_obstacle_topic: /obstacles
    model_path: /perception_models/yolov8s.pt
    image_size: 480
