eve_camera_object_detection:
  ros__parameters:
    front_right_camera_topic: /right_camera/image_color
    front_center_camera_topic: /front_camera/image_color
    front_left_camera_topic: /left_camera/image_color
    publish_vis_topic: false
    eve_batch_inference_topic: /camera/left/camera_detections
    model_path: /perception_models/yolov8m.pt
    image_size: 640
    compressed: true
    nuscenes: false

