left_camera_object_detection_node:
  ros__parameters:
    camera_topic: /camera/left/image_color
    publish_vis_topic: /camera/left/camera_detections_viz
    publish_detection_topic: /camera/left/camera_detections
    model_path: /perception_models/yolov8s.pt
    image_size: 480

center_camera_object_detection_node:
  ros__parameters:
    camera_topic: /camera/center/image_color
    publish_vis_topic: /camera/center/camera_detections_viz
    publish_detection_topic: /camera/center/camera_detections
    model_path: /perception_models/yolov8s.pt
    image_size: 480

right_camera_object_detection_node:
  ros__parameters:
    camera_topic: /camera/right/image_color
    publish_vis_topic: /camera/right/camera_detections_viz
    publish_detection_topic: /camera/right/camera_detections
    model_path: /perception_models/yolov8s.pt
    image_size: 480
