traffic_light_node:
  ros__parameters:
    camera_topic: /camera/left/image_color
    publish_vis_topic: /annotated_traffic_lights
    publish_detection_topic: /traffic_lights
    model_path: /perception_models/traffic_light.pt
    crop_mode: CenterCrop
    image_size: 1024
    save_detections: false
