novatel/oem7/novatel_oem7_driver:
  ros__parameters:
    # OEM7 Driver Configuration
    oem7_max_io_errors: 10
    oem7_msg_decoder: "Oem7MessageDecoder"
    oem7_position_source: ""  # Options: "", "gps", "ins", etc.
    oem7_imu_rate: 100  # Hz, 0 to disable IMU output
    oem7_odometry_zero_origin: false
    oem7_odometry_transform: false
    oem7_receiver_log_file: ""  # Path to log file or empty to disable
    oem7_decoder_log_file: ""  # Path to log file or empty to disable
    oem7_strict_receiver_init: true
    oem7_publish_unknown_oem7raw: false
    oem7_publish_delay: 0.0
    
    # Frame IDs
    gps_frame_id: "gps"
    imu_frame_id: "imu"
    
    # Topic configuration
    oem7_raw_topic: "oem7/raw"
    oem7_corrimu_topic: "oem7/corrimu"
    oem7_insconfig_topic: "oem7/insconfig"
    oem7_insstdev_topic: "oem7/insstdev"
    oem7_inspva_topic: "oem7/inspva"
    oem7_inspvax_topic: "oem7/inspvax"
    oem7_bestpos_topic: "oem7/bestpos"
    oem7_bestvel_topic: "oem7/bestvel"
    oem7_bestutm_topic: "oem7/bestutm"
    oem7_time_topic: "oem7/time"
    oem7_rxstatus_topic: "oem7/rxstatus"
