---
velodyne_driver_node:
  ros__parameters:
    device_ip: 10.8.0.88
    gps_time: false
    time_offset: 0.0
    enabled: true
    read_once: false
    read_fast: false
    repeat_delay: 0.0
    frame_id: lidar_top
    model: 32C
    rpm: 600.0
    port: 2368
    timestamp_first_packet: false
