ars_point_cloud_filter:
  ros__parameters:
    filter_mode: "ars"
    vrel_rad: -99999.99
    el_ang: -99999.99
    rcs0: -99999.99
    snr: -99999.99
    range: -99999.99
    az_ang0: -99999.99
    scan_mode: "near"
