camera_detection_node:
  ros__parameters:
    camera_topic: /CAM_FRONT/image_rect_compressed
    publish_vis_topic: /annotated_img
    publish_obstacle_topic: /obstacles
    model_path: /perception_models/yolov8s.pt
    image_size: 640
    compressed: true
