name: Generate Docker Environment

inputs:
  modified_modules:
    description: "Space deliminated list of modified modules"
    required: true
    default: ''

outputs:
  docker_matrix:
    description: "list of docker compose services"
    value: ${{ steps.environment-generator.outputs.docker_matrix }}
  registry:
    description: "name of the docker registry we are using"
    value: ${{ steps.environment-generator.outputs.registry }}
  repository:
    description: "name of the docker repository we are using"
    value: ${{ steps.environment-generator.outputs.repository }}

runs:
  using: "composite"
  steps:
    - id: environment-generator
      env: 
        MODIFIED_MODULES: ${{ inputs.modified_modules }}
      run: ${{ github.action_path }}/docker_context.sh
      shell: bash
