---
launch:
  - arg:
      name: "lidar_config_file"
      description: "Path to Top LiDAR configuration file"

  - node_container:
      pkg: rclcpp_components
      exec: component_container
      name: lidar_top_container
      namespace: "lidar_top"

  - node_container:
      pkg: rclcpp_components
      exec: component_container
      name: lidar_left_container
      namespace: "lidar_left"

  - node_container:
      pkg: rclcpp_components
      exec: component_container
      name: lidar_right_container
      namespace: "lidar_right"

  - node_container:
      target: lidar_top_container
      composable_node:
        - pkg: velodyne_driver
          plugin: velodyne_driver::VelodyneDriver
          name: velodyne_driver_node_top
          param:
            - from: "$(var lidar_config_file)"

        - pkg: velodyne_pointcloud
          plugin: velodyne_pointcloud::Transform
          name: velodyne_transform_node_top
          param:
            - from: "$(find-pkg-share velodyne_pointcloud)/config/VLP32C-velodyne_transform_node-params.yaml"
            - name: calibration
              value: "$(find-pkg-share velodyne_pointcloud)/params/VeloView-VLP-32C.yaml"

        - pkg: velodyne_laserscan
          plugin: velodyne_laserscan::VelodyneLaserScan
          name: velodyne_laserscan_node_top
          param:
            - from: "$(find-pkg-share velodyne_laserscan)/config/default-velodyne_laserscan_node-params.yaml"

  - node_container:
      target: lidar_left_container
      composable_node:
        - pkg: velodyne_driver
          plugin: velodyne_driver::VelodyneDriver
          name: velodyne_driver_node_left
          param:
            - from: "$(var lidar_config_file)"

        - pkg: velodyne_pointcloud
          plugin: velodyne_pointcloud::Transform
          name: velodyne_transform_node_left
          param:
            - from: "$(find-pkg-share velodyne_pointcloud)/config/VLP16-velodyne_transform_node-params.yaml"
            - name: calibration
              value: "$(find-pkg-share velodyne_pointcloud)/params/VLP16db.yaml"

        - pkg: velodyne_laserscan
          plugin: velodyne_laserscan::VelodyneLaserScan
          name: velodyne_laserscan_node_left
          param:
            - from: "$(find-pkg-share velodyne_laserscan)/config/default-velodyne_laserscan_node-params.yaml"

  - node_container:
      target: lidar_right_container
      composable_node:
        - pkg: velodyne_driver
          plugin: velodyne_driver::VelodyneDriver
          name: velodyne_driver_node_right
          param:
            - from: "$(var lidar_config_file)"

        - pkg: velodyne_pointcloud
          plugin: velodyne_pointcloud::Transform
          name: velodyne_transform_node_right
          param:
            - from: "$(find-pkg-share velodyne_pointcloud)/config/VLP16-velodyne_transform_node-params.yaml"
            - name: calibration
              value: "$(find-pkg-share velodyne_pointcloud)/params/VLP16db.yaml"

        - pkg: velodyne_laserscan
          plugin: velodyne_laserscan::VelodyneLaserScan
          name: velodyne_laserscan_node_right
          param:
            - from: "$(find-pkg-share velodyne_laserscan)/config/default-velodyne_laserscan_node-params.yaml"
