---
launch:
  - arg:
      name: "lidar_config_file"
      description: "Path to Top LiDAR configuration file"

  - node_container:
      pkg: rclcpp_components
      exec: component_container
      name: lidar_top_container
      namespace: ""

  - node_container:
      pkg: rclcpp_components
      exec: component_container
      name: lidar_left_container
      namespace: ""

  - node_container:
      pkg: rclcpp_components
      exec: component_container
      name: lidar_right_container
      namespace: ""

  - load_composable_node:
      target: lidar_top_container
      composable_node:
        - pkg: velodyne_driver
          plugin: velodyne_driver::VelodyneDriver
          name: velodyne_driver_node_top
          remap:
            - from: "velodyne_packets"
              to: "lidar_top/velodyne_packets"
          param:
            - from: "$(var lidar_config_file)"

        - pkg: velodyne_pointcloud
          plugin: velodyne_pointcloud::Transform
          name: velodyne_transform_node_top
          remap:
            - from: "velodyne_packets"
              to: "lidar_top/velodyne_packets"
            - from: "velodyne_points"
              to: "lidar_top/velodyne_points"
          param:
            - from: "$(find-pkg-share velodyne_pointcloud)/config/VLP32C-velodyne_transform_node-params.yaml"
            - name: calibration
              value: "$(find-pkg-share velodyne_pointcloud)/params/VeloView-VLP-32C.yaml"

        - pkg: velodyne_laserscan
          plugin: velodyne_laserscan::VelodyneLaserScan
          name: velodyne_laserscan_node_top
          remap:
            - from: "velodyne_points"
              to: "lidar_top/velodyne_points"
            - from: "scan"
              to: "lidar_top/scan"
          param:
            - from: "$(find-pkg-share velodyne_laserscan)/config/default-velodyne_laserscan_node-params.yaml"

  - load_composable_node:
      target: lidar_left_container
      composable_node:
        - pkg: velodyne_driver
          plugin: velodyne_driver::VelodyneDriver
          name: velodyne_driver_node_left
          remap:
            - from: "velodyne_packets"
              to: "lidar_left/velodyne_packets"
          param:
            - from: "$(var lidar_config_file)"

        - pkg: velodyne_pointcloud
          plugin: velodyne_pointcloud::Transform
          name: velodyne_transform_node_left
          remap:
            - from: "velodyne_packets"
              to: "lidar_left/velodyne_packets"
            - from: "velodyne_points"
              to: "lidar_left/velodyne_points"
          param:
            - from: "$(find-pkg-share velodyne_pointcloud)/config/VLP16-velodyne_transform_node-params.yaml"
            - name: calibration
              value: "$(find-pkg-share velodyne_pointcloud)/params/VLP16db.yaml"

        - pkg: velodyne_laserscan
          plugin: velodyne_laserscan::VelodyneLaserScan
          name: velodyne_laserscan_node_left
          remap:
            - from: "velodyne_points"
              to: "lidar_left/velodyne_points"
            - from: "scan"
              to: "lidar_left/scan"
          param:
            - from: "$(find-pkg-share velodyne_laserscan)/config/default-velodyne_laserscan_node-params.yaml"

  - load_composable_node:
      target: lidar_right_container
      composable_node:
        - pkg: velodyne_driver
          plugin: velodyne_driver::VelodyneDriver
          name: velodyne_driver_node_right
          remap:
            - from: "velodyne_packets"
              to: "lidar_right/velodyne_packets"
          param:
            - from: "$(var lidar_config_file)"

        - pkg: velodyne_pointcloud
          plugin: velodyne_pointcloud::Transform
          name: velodyne_transform_node_right
          remap:
            - from: "velodyne_packets"
              to: "lidar_right/velodyne_packets"
            - from: "velodyne_points"
              to: "lidar_right/velodyne_points"
          param:
            - from: "$(find-pkg-share velodyne_pointcloud)/config/VLP16-velodyne_transform_node-params.yaml"
            - name: calibration
              value: "$(find-pkg-share velodyne_pointcloud)/params/VLP16db.yaml"

        - pkg: velodyne_laserscan
          plugin: velodyne_laserscan::VelodyneLaserScan
          name: velodyne_laserscan_node_right
          remap:
            - from: "velodyne_points"
              to: "lidar_right/velodyne_points"
            - from: "scan"
              to: "lidar_right/scan"
          param:
            - from: "$(find-pkg-share velodyne_laserscan)/config/default-velodyne_laserscan_node-params.yaml"
