tracker_node:
  ros__parameters:
    max_age: 6
    min_hits: 2
    reference_frame: map
    default_distance_threshold: 3
    velocity_filter_constant: 5.0
    velocity_prediction_horizon: 0.5
    prediction_resolution: 0.5
    prediction_length: 4.0
      #sub_det3d: False

tracking_viz:
  ros__parameters:
    image_topic: /annotated_img
    publish_viz_topic: /annotated_3d_img
      #det_3d_topic: /detections_3d
    camera_info_topic: /CAM_FRONT/camera_info
    camera_frame: CAM_FRONT
    lidar_frame: LIDAR_TOP
    global_frame: map
    viz_tracks: True
    viz_dets: True
    pub_markers: True
    pub_images: True
    skip_missed_frames: True
    box_line_width: 5
    # setting skip_missed_frames to False causes mem leak i think

/**:
  ros__parameters:
    sub_det3d: False
    det_3d_topic: /detections
    marker_topic: /markers/annotations
    track_topic: /tracked_obstacles 
