semantic_segmentation_node:
  ros__parameters:
    input_topic: "/CAM_FRONT/image_rect_compressed"
    publish_topic: "/camera/left/segmentations"
    config: "model/segformer_mit-b2_8xb1-160k_cityscapes-1024x1024.py"
    checkpoint: "model/segformer_mit-b2_8x1_1024x1024_160k_cityscapes_20211207_134205-6096669a.pth"
    MODEL_IMAGE_H: 1024
    MODEL_IMAGE_W: 1024