<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fake_planner</name>
  <version>0.0.0</version>
  <description>Fake planner that replays a predefined trajectory from a waypoints file, for controller SIL and real-vehicle testing</description>
  <maintainer email="b69zheng@uwaterloo.ca">Brian Zheng</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>behaviour_msgs</depend>
  <depend>wato_trajectory_msgs</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>std_srvs</depend>
  <depend>visualization_msgs</depend>

  <exec_depend>ackermann_pure_pursuit</exec_depend>
  <exec_depend>mpc_controller</exec_depend>
  <exec_depend>action_bringup</exec_depend>
  <exec_depend>wato_lifecycle_manager</exec_depend>

  <test_depend>wato_test</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
