---
patchworkpp_node:
  ros__parameters:
    # Patchwork++ parameters (seeded from library defaults)
    sensor_height: 1.84 #lidar height specific to nuscenes, change this for eve
    num_iter: 3
    num_lpr: 20
    num_min_pts: 0
    th_seeds: 0.3
    th_dist: 0.15
    th_seeds_v: 0.25
    th_dist_v: 0.85
    max_range: 90.0
    min_range: 1.0
    uprightness_thr: 0.101
    enable_RNR: false
    verbose: false
