name: Generate environment

outputs:
  context:
    description: "absolute path to each dockerfile and service name"
    value: ${{ steps.environment-generator.outputs.context }}
  profiles:
    description: "space delimited string of supported profiles"
    value: ${{ steps.environment-generator.outputs.profiles }}

runs:
  using: "composite"
  steps:
    - id: environment-generator
      run: ${{ github.action_path }}/docker_context.sh
      shell: bash

