# ExecuteBehaviour.action
# Deprecated method of sending the lane behaviour to lattice planner

# Request
string behaviour
---
# Result
string success
string error_message
---
# Feedback
string feedback_message
