<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Vehicle Properties -->
  <xacro:property name="length" value="4.0936"/>
  <xacro:property name="width" value="1.3579"/>
  <xacro:property name="height" value="1.4090"/>
  <xacro:property name="wheel_radius" value="0.31235"/>
  <xacro:property name="wheel_width" value="0.2137"/>
  <xacro:property name="wheelbase" value="2.5667"/>
  <xacro:property name="track_width" value="1.5716"/>

  <!-- Chassis macro - allows parent specification -->
  <xacro:macro name="chassis" params="parent *origin">
    <!-- Chassis Link -->
    <link name="chassis">
      <visual>
        <origin xyz="${wheelbase/2 + 0.065} 0 0" rpy="-${pi/2} 0 ${pi/2}"/>
        <geometry>
          <mesh filename="package://eve_description/meshes/kia_soul_ev.stl" scale="0.01 0.01 0.01"/>
        </geometry>
        <material name="grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
    </link>

    <!-- Joint from parent to chassis -->
    <joint name="base_to_chassis" type="fixed">
      <parent link="${parent}"/>
      <child link="chassis"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <!-- Axle center frames (at wheel-center height) -->
    <link name="rear_axle"/>
    <joint name="rear_axle_joint" type="fixed">
      <parent link="chassis"/>
      <child link="rear_axle"/>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="front_axle"/>
    <joint name="front_axle_joint" type="fixed">
      <parent link="chassis"/>
      <child link="front_axle"/>
      <origin xyz="${wheelbase} 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- Wheel Macro -->
    <xacro:macro name="wheel" params="parent name y">
      <link name="${name}_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="black">
            <color rgba="0.0 0.0 0.0 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>
      </link>
      <joint name="${name}_joint" type="continuous">
        <parent link="${parent}"/>
        <child link="${name}_wheel"/>
        <origin xyz="0 ${y} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
      </joint>
    </xacro:macro>

    <!-- Steering Wheel Macro -->
    <xacro:macro name="steering_wheel" params="parent name y">
      <link name="${name}_knuckle"/>
      <joint name="${name}_steering_joint" type="revolute">
        <parent link="${parent}"/>
        <child link="${name}_knuckle"/>
        <origin xyz="0 ${y} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="10" velocity="1" lower="-0.785" upper="0.785"/> <!-- +/-45 deg -->
      </joint>
      <link name="${name}_wheel">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="black">
            <color rgba="0.0 0.0 0.0 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>
      </link>
      <joint name="${name}_wheel_joint" type="continuous">
        <parent link="${name}_knuckle"/>
        <child link="${name}_wheel"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
      </joint>
    </xacro:macro>

    <!-- Rear Wheels (children of rear_axle) -->
    <xacro:wheel parent="rear_axle" name="rear_left" y="${track_width/2}"/>
    <xacro:wheel parent="rear_axle" name="rear_right" y="-${track_width/2}"/>

    <!-- Front Wheels with Steering (children of front_axle) -->
    <xacro:steering_wheel parent="front_axle" name="front_left" y="${track_width/2}"/>
    <xacro:steering_wheel parent="front_axle" name="front_right" y="-${track_width/2}"/>
  </xacro:macro>

</robot>
