<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Roof mount macro - allows parent specification -->
  <xacro:macro name="roof_mount" params="parent *origin">
    <!-- Roof mount for all sensors -->
    <link name="roof_mount"/>
    <joint name="roof_mount_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="roof_mount"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <!-- Top LiDAR -->
    <link name="lidar_top">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.1" length="0.15"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.1" length="0.15"/>
        </geometry>
      </collision>
    </link>

    <joint name="lidar_top_mount_yaw" type="fixed">
      <parent link="roof_mount"/>
      <child link="lidar_top"/>
      <origin xyz="0 0 0.35" rpy="0 0 0"/>
    </joint>


    <!-- GPS/IMU Antenna -->
    <link name="gps_imu_antenna">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.08"/>
        </geometry>
        <material name="blue">
          <color rgba="0.0 0.0 1.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.08"/>
        </geometry>
      </collision>
    </link>

    <joint name="gps_imu_mount_yaw" type="fixed">
      <parent link="roof_mount"/>
      <child link="gps_imu_antenna"/>
      <origin xyz="-0.5600 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:property name="camera_z" value="0.217"/>
    <xacro:property name="pano_radius" value="0.240676"/>
    <xacro:property name="pano_cameras" value="8"/>
    <xacro:property name="angle_increment" value="${2*pi/pano_cameras}"/>

    <xacro:macro name="create_camera" params="index name">
      <xacro:property name="angle" value="${-pi/4 - index * angle_increment}"/>
      <xacro:property name="cam_x" value="${pano_radius * cos(angle)}"/>
      <xacro:property name="cam_y" value="${pano_radius * sin(angle)}"/>

      <link name="camera_pano_${name}">
        <visual>
          <origin xyz="0 0 0" rpy="${-pi/2.0} 0 ${-pi/2.0}"/>
          <geometry>
            <sphere radius="0.05"/>
          </geometry>
          <material name="red">
            <color rgba="1.0 0.0 0.0 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="${-pi/2.0} 0 ${-pi/2.0}"/>
          <geometry>
            <sphere radius="0.05"/>
          </geometry>
        </collision>
      </link>

      <!-- the additional rotation of -pi/2 is to go from FLU to RDF coordinate systems -->
      <joint name="camera_pano_${name}_mount" type="fixed">
        <parent link="roof_mount"/>
        <child link="camera_pano_${name}"/>
        <origin xyz="${cam_x} ${cam_y} ${camera_z}" rpy="${-pi/2} 0 ${angle - pi/2}"/>
      </joint>
    </xacro:macro>


    <xacro:create_camera index="0" name="ne"/>
    <xacro:create_camera index="1" name="ee"/>
    <xacro:create_camera index="2" name="se"/>
    <xacro:create_camera index="3" name="ss"/>
    <xacro:create_camera index="4" name="sw"/>
    <xacro:create_camera index="5" name="ww"/>
    <xacro:create_camera index="6" name="nw"/>
    <xacro:create_camera index="7" name="nn"/>
  </xacro:macro>

</robot>
