<?xml version="1.0"?>
<robot name="eve_kia_soul_ev" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="length" value="4.14"/>
  <xacro:property name="width" value="1.80"/>
  <xacro:property name="height" value="1.60"/>
  <xacro:property name="wheel_radius" value="0.3"/>
  <xacro:property name="wheel_width" value="0.2"/>
  <xacro:property name="wheelbase" value="2.51"/>
  <xacro:property name="track_width" value="1.52"/>

  <link name="base_link">
    <visual>
      <origin xyz="${wheelbase/2} 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
  </link>

  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_wheel"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="steering_wheel" params="name x y z">
    <link name="${name}_knuckle"/>
    <joint name="${name}_steering_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${name}_knuckle"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="10" velocity="1" lower="-0.785" upper="0.785"/> <!-- +/-45 deg -->
    </joint>
    <link name="${name}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="${name}_knuckle"/>
      <child link="${name}_wheel"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- 6-DOF sensor mount for online calibration using floating joint -->
  <!-- Allows small adjustments in all 6 degrees of freedom -->
  <xacro:macro name="sensor_6dof_mount" params="name parent_link child_link x y z roll pitch yaw">
    <joint name="${name}_floating_joint" type="floating">
      <parent link="${parent_link}"/>
      <child link="${child_link}"/>
      <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
    </joint>
  </xacro:macro>

  <!-- Rear Wheels -->
  <xacro:wheel name="rear_left" x="0" y="${track_width/2}" z="${wheel_radius}"/>
  <xacro:wheel name="rear_right" x="0" y="-${track_width/2}" z="${wheel_radius}"/>

  <!-- Front Wheels with Steering -->
  <xacro:steering_wheel name="front_left" x="${wheelbase}" y="${track_width/2}" z="${wheel_radius}"/>
  <xacro:steering_wheel name="front_right" x="${wheelbase}" y="-${track_width/2}" z="${wheel_radius}"/>

<link name="lidar_top">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="0.1" length="0.15"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="0.1" length="0.15"/>
    </geometry>
  </collision>
</link>

<xacro:sensor_6dof_mount name="lidar_top_mount" parent_link="base_link" child_link="lidar_top"
                          x="-0.55" y="0" z="2.07" roll="0" pitch="0" yaw="0"/>

<!-- Left Mirror LiDAR -->
<link name="lidar_left">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="0.08" length="0.12"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="0.08" length="0.12"/>
    </geometry>
  </collision>
</link>

<xacro:sensor_6dof_mount name="lidar_left_mount" parent_link="base_link" child_link="lidar_left"
                          x="-0.55" y="1" z="2.07" roll="0" pitch="0" yaw="2"/>

<!-- Right Mirror LiDAR -->
<link name="lidar_right">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="0.08" length="0.12"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="0.08" length="0.12"/>
    </geometry>
  </collision>
</link>

<xacro:sensor_6dof_mount name="lidar_right_mount" parent_link="base_link" child_link="lidar_right"
                          x="-0.55" y="-1" z="2.07" roll="0" pitch="0" yaw="2"/>

<!-- GPS/IMU Antenna -->
<link name="gps_imu_antenna">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="0.05"/>
    </geometry>
    <material name="blue">
      <color rgba="0.0 0.0 1.0 1"/>
    </material>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <sphere radius="0.05"/>
    </geometry>
  </collision>
</link>

<xacro:sensor_6dof_mount name="gps_imu_mount" parent_link="base_link" child_link="gps_imu_antenna"
                          x="-1.0326" y="0" z="1.689" roll="0" pitch="0" yaw="0"/>

</robot>
