<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Roof mount macro - allows parent specification -->
  <xacro:macro name="roof_mount" params="parent *origin">
    <!-- Roof mount for all sensors -->
    <link name="roof_mount"/>
    <joint name="roof_mount_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="roof_mount"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <!-- Top LiDAR -->
    <link name="lidar_top">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.1" length="0.15"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.1" length="0.15"/>
        </geometry>
      </collision>
    </link>

    <joint name="lidar_top_mount_yaw" type="fixed">
      <parent link="roof_mount"/>
      <child link="lidar_top"/>
      <origin xyz="0 0 0.35" rpy="0 0 0"/>
    </joint>


    <!-- GPS/IMU Antenna -->
    <link name="gps_imu_antenna">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.08"/>
        </geometry>
        <material name="blue">
          <color rgba="0.0 0.0 1.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.08"/>
        </geometry>
      </collision>
    </link>

    <joint name="gps_imu_mount_yaw" type="fixed">
      <parent link="roof_mount"/>
      <child link="gps_imu_antenna"/>
      <origin xyz="-0.5600 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:property name="camera_z" value="0.217"/>
    <xacro:property name="pano_radius" value="0.240676"/>

    <!-- Roof-Mounted Cameras -->
    <link name="camera_nn">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
        <material name="red">
          <color rgba="1.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
    </link>


    <joint name="camera_nn_mount_yaw" type="fixed">
      <parent link="roof_mount"/>
      <child link="camera_nn"/>
      <origin xyz="${pano_radius} 0 ${camera_z}" rpy="0 0 0"/>
    </joint>

    <link name="camera_pano_nw">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
        <material name="red">
          <color rgba="1.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
    </link>

    <joint name="camera_pano_nw_mount_yaw" type="fixed">
      <parent link="roof_mount"/>
      <child link="camera_pano_nw"/>
      <origin xyz="${pano_radius/sqrt(2)} ${pano_radius/sqrt(2)} ${camera_z}" rpy="0 0 ${pi/4}"/>
    </joint>


    <link name="camera_pano_ne">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
        <material name="red">
          <color rgba="1.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
      </collision>
    </link>

    <joint name="camera_pano_ne_mount_yaw" type="fixed">
      <parent link="roof_mount"/>
      <child link="camera_pano_ne"/>
      <origin xyz="${pano_radius/sqrt(2)} -${pano_radius/sqrt(2)} ${camera_z}" rpy="0 -0 -${pi/4}"/>
    </joint>
  </xacro:macro>

</robot>
