receiver_init_commands:
  # Reset logging
  - "UNLOGALL THISPORT"

  # Enable PPS output for Velodyne lidar time synchronization
  - "PPSCONTROL ENABLE POSITIVE 1.0 1000"

  # Output GPRMC sentence every second (required by Velodyne for GPS time)
  - "LOG GPRMC ONTIME 1"

  # Standard Logging Requests (from std_init_commands.yaml)
  - "LOG INSCONFIGB ONCE"
  - "LOG TERRASTARINFOB ONCE"
  - "LOG TERRASTARSTATUSB ONCE"
  - "LOG TERRASTARINFOB ONTIME 300"
  - "LOG TERRASTARSTATUSB ONTIME 300"
  - "LOG INSCONFIGB ONTIME 300"
  - "LOG RXSTATUSB ONCHANGED"
  - "LOG BESTPOSB ONTIME 0.1"
  - "LOG BESTVELB ONTIME 0.1"
  - "LOG BESTGNSSVELB ONTIME 0.1"
  - "LOG BESTUTMB ONTIME 1"
  - "LOG BESTGNSSPOSB ONTIME 0.1"
  - "LOG PPPPOSB ONTIME 1"
  - "LOG HEADING2B ONNEW"
  - "LOG PSRDOP2B ONCHANGED"
  - "LOG INSPVASB ONTIME 0.02"
  - "LOG INSPVAXB ONTIME 1"
  - "LOG CORRIMUSB ONTIME 0.01"
  - "LOG INSSTDEVB ONTIME 1"
  - "LOG RAWIMUSXB ONNEW"
  - "LOG TIMEB ONTIME 1"
  - "LOG VERSIONB ONCE"
  - "LOG INSUPDATESTATUSB ONNEW"
  - "LOG RAWEPHEMB ONNEW"
  - "LOG GLOEPHEMERISB ONNEW"
  - "LOG BDSEPHEMERISB ONNEW"
  - "LOG GALFNAVEPHEMERISB ONNEW"
  - "LOG GALINAVEPHEMERISB ONNEW"
  - "LOG RANGEB ONTIME 1"
