# Camera configuration for three FLIR Blackfly cameras
# Common parameters shared by all cameras

# Camera-specific serial numbers
flir_camera_0/camera:
  ros__parameters:
    debug: false
    dump_node_map: false
    pixel_format: BayerRG8
    exposure_auto: 'On'
    exposure_time: 9000
    gain_auto: 'Off'
    gain: 0.0
    trigger_mode: 'Off'
    frame_rate_enable: true
    frame_rate: 60.0
    frame_rate_auto: 'Off'
    buffer_queue_size: 1000
    stream_buffer_handling_mode: NewestOnly
    multicast_monitor_mode: false
    gev_scps_packet_size: 9000
    serial_number: '18542606'

flir_camera_1/camera:
  ros__parameters:
    debug: false
    dump_node_map: false
    pixel_format: BayerRG8
    exposure_auto: 'On'
    exposure_time: 9000
    gain_auto: 'Off'
    gain: 0.0
    trigger_mode: 'Off'
    frame_rate_enable: true
    frame_rate: 60.0
    frame_rate_auto: 'Off'
    buffer_queue_size: 1000
    stream_buffer_handling_mode: NewestOnly
    multicast_monitor_mode: false
    gev_scps_packet_size: 9000
    serial_number: '17453304'

flir_camera_2/camera:
  ros__parameters:
    debug: false
    dump_node_map: false
    pixel_format: BayerRG8
    exposure_auto: 'On'
    exposure_time: 9000
    gain_auto: 'Off'
    gain: 0.0
    trigger_mode: 'Off'
    frame_rate_enable: true
    frame_rate: 60.0
    frame_rate_auto: 'Off'
    buffer_queue_size: 1000
    stream_buffer_handling_mode: NewestOnly
    multicast_monitor_mode: false
    gev_scps_packet_size: 9000
    serial_number: '17453317'
