version: "3.8"
services:
  traffic_light_detection:
    build:
      context: ..
      dockerfile: docker/perception/traffic_light_detection.Dockerfile
      cache_from: 
        - "${TRAFFIC_LIGHT_DETECTION_IMAGE:?}:${TAG}"
        - "${TRAFFIC_LIGHT_DETECTION_IMAGE:?}:main"
    image: "${TRAFFIC_LIGHT_DETECTION_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/perception/traffic_light_detection:/home/docker/ament_ws/src/traffic_light_detection
