version: "3.8"
services:
  carla_server:
    build:
      context: ..
      dockerfile: docker/carla_server/Dockerfile
      # cache_from:
      #   - "${CARLA_SERVER_IMAGE:?}-${CACHE_FROM_TAG}"
      #   - "${CARLA_SERVER_IMAGE:?}-develop"
      args:
        - CARLA_VERSION=0.9.14
    container_name: ${COMPOSE_PROJECT_NAME:?}_carla
    runtime: nvidia
    command: /bin/bash -c "./CarlaUE4.sh -quality-level=1 -world-port=2000 -nosound -carla-server -RenderOffscreen"

  carla_ros_bridge:
    build:
      context: ..
      dockerfile: docker/carla_ros_bridge/Dockerfile
      args:
        - CARLA_VERSION=0.9.14
    container_name: ${COMPOSE_PROJECT_NAME:?}_carla_ros_bridge
    runtime: nvidia
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: tail -F anything
    depends_on:
      - carla_server
