version: "3.8"
services:
  aggregator:
    build:
      context: ..
      dockerfile: docker/samples/cpp/Dockerfile.aggregator
    image: "aggregator"
    # user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/samples/cpp/aggregator:/home/docker/ament_ws/src/aggregator
  producer:
    build:
      context: ..
      dockerfile: docker/samples/cpp/Dockerfile.producer
    image: "producer"
    # user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/samples/cpp/producer:/home/docker/ament_ws/src/producer
  transformer:
    build:
      context: ..
      dockerfile: docker/samples/cpp/Dockerfile.transformer
    image: "transformer"
    # user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ./src/samples/cpp/transformer:/home/docker/ament_ws/src/transformer
