version: "3.8"
services:
  radar_centerfusion:
    build:
      context: ..
      dockerfile: docker/radar_object_detection/radar_centerfusion.Dockerfile
      cache_from: 
        - "${RADAR_CENTERFUSION_IMAGE:?}:${CACHE_FROM_TAG}"
        - "${RADAR_CENTERFUSION_IMAGE:?}:develop"
    image: "${RADAR_CENTERFUSION_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/perception/radar_object_detection/radar_centerfusion:/home/docker/ament_ws/src/radar_centerfusion

  radar_inference:
    build:
      context: ..
      dockerfile: docker/radar_object_detection/radar_inference.Dockerfile
      cache_from: 
        - "${RADAR_INFERENCE_IMAGE:?}:${CACHE_FROM_TAG}"
        - "${RADAR_INFERENCE_IMAGE:?}:develop"
    image: "${RADAR_INFERENCE_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    ipc: host
    tty: true
    volumes:
      - /mnt/wato-drive/perception/nuscenes_CLEAN
      - ../src/testing_pretrained:/home/docker/ament_ws/src/testing_pretrained
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]