version: "3.8"
services:
  # aggregator:
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/python/Dockerfile.aggregator
    #   cache_from:
    #     - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}-${CACHE_FROM_TAG}"
    #     - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}-develop"
    # image: "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}-${TAG}"
    # user: ${FIXUID:?}:${FIXGID:?}
    # volumes:
    #   - ../src/samples/python/aggregator:/home/docker/ament_ws/src/aggregator
  producer:
    build:
      context: ..
      dockerfile: docker/samples/python/Dockerfile.producer
      cache_from:
        - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}-develop"
    image: "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}-${TAG}"
    # command: tail -F anything
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/samples/python/producer:/home/docker/ament_ws/src/producer
  transformer:
    build:
      context: ..
      dockerfile: docker/samples/python/Dockerfile.transformer
      cache_from:
        - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}-develop"
    image: "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}-${TAG}"
    # command: tail -F anything
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/samples/python/transformer:/home/docker/ament_ws/src/transformer