version: "3.8"
services:
  carla_server:
    build:
      context: ..
      dockerfile: docker/carla_server/Dockerfile
      cache_from:
        - "${CARLA_SERVER_IMAGE:?}:latest"
      args:
        - CARLA_VERSION=0.9.13
    image: "${CARLA_SERVER_IMAGE:?}:latest"
    container_name: ${COMPOSE_PROJECT_NAME:?}_carla
    runtime: nvidia
    # ports:
    #   - 2000-2002:2000-2002
    ports:
      - 2000:2000
    command: /bin/bash -c "./CarlaUE4.sh -nosound -carla-server -RenderOffscreen -world-port=2000"
    #command: ["tail", "-f", "/dev/null"]

  carla_ros_bridge:
    build:
      context: ..
      dockerfile: docker/carla_ros_bridge/Dockerfile
      cache_from: 
        - "${CARLA_ROS2_BRIDGE_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${CARLA_ROS2_BRIDGE_IMAGE:?}-develop"
      args:
        - CARLA_VERSION=0.9.13
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    image: "${CARLA_ROS2_BRIDGE_IMAGE:?}-${TAG}" 
    container_name: ${COMPOSE_PROJECT_NAME:?}_carla_ros_bridge
    runtime: nvidia
    #stdin_open: true # docker run -i
    #tty: true # docker run -t
    #command: ["tail", "-f", "/dev/null"]
    #command: ["ros2", "launch", "carla_ros_bridge", "carla_ros_bridge.launch.py", "host:=${COMPOSE_PROJECT_NAME:?}_carla", "timeout:=200"]
    restart: always
    depends_on:
      - carla_server

  carla_bridge:
    build: 
      context: ..
      dockerfile: docker/simulation/Dockerfile
    #user: ${FIXUID:?}:${FIXGID:?}
    user: root:root
    # depends_on:
    #   - carla_server
    #   - carla_ros_bridge
