version: "3.8"
services:
  # radar_object_detection:
  #   build:
  #     context: ..
  #     dockerfile: docker/perception/radar_object_detection.Dockerfile
  #     cache_from: 
  #       - "${RADAR_OBJECT_DETECTION_IMAGE:?}:${TAG}"
  #       - "${RADAR_OBJECT_DETECTION_IMAGE:?}:main"
  #   image: "${RADAR_OBJECT_DETECTION_IMAGE:?}:${TAG}"
  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ../src/perception/radar_object_detection:/home/docker/ament_ws/src/radar_object_detection
  lane_detection:
    build:
      context: ..
      dockerfile: docker/perception/lane_detection.Dockerfile
      cache_from: 
        - "${LANE_DETECTION_IMAGE:?}:${TAG}"
        - "${LANE_DETECTION_IMAGE:?}:main"
    image: "${LANE_DETECTION_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      # mount the model (ufldv2_culane_res34_320x1600.onnx)
      - /mnt/wato-drive2/perception-weights/tensorrt_model/ultra_fast_lane_detection_v2/resource/model/ufldv2_culane_res34_320x1600.onnx:/home/docker/ament_ws/build/lane_detection/resource/model/ufldv2_culane_res34_320x1600.onnx
