version: "3.8"
services:
  # radar_object_detection:
  #   build:
  #     context: ..
  #     dockerfile: docker/perception/radar_object_detection.Dockerfile
  #     cache_from: 
  #       - "${RADAR_OBJECT_DETECTION_IMAGE:?}:${TAG}"
  #       - "${RADAR_OBJECT_DETECTION_IMAGE:?}:main"
  #   image: "${RADAR_OBJECT_DETECTION_IMAGE:?}:${TAG}"
  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ../src/perception/radar_object_detection:/home/docker/ament_ws/src/radar_object_detection
  lidar_object_detection:
    build:
      context: ..
      dockerfile: docker/perception/lidar_object_detection.Dockerfile
      cache_from:
        - "${LIDAR_OBJECT_DETECTION_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${LIDAR_OBJECT_DETECTION_IMAGE:?}-develop"
    image: "${LIDAR_OBJECT_DETECTION_IMAGE:?}-${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/perception/lidar_object_detection:/home/docker/ament_ws/src/lidar_object_detection
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]