version: "3.8"
services:
  aggregator:
    build:
      context: ..
      dockerfile: docker/samples/cpp/aggregator.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}-develop"
    image: "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}-${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/samples/cpp/aggregator:/home/docker/ament_ws/src/aggregator
  producer:
    build:
      context: ..
      dockerfile: docker/samples/cpp/producer.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_PRODUCER_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${SAMPLES_CPP_PRODUCER_IMAGE:?}-develop"
    image: "${SAMPLES_CPP_PRODUCER_IMAGE:?}-${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/samples/cpp/producer:/home/docker/ament_ws/src/producer
  transformer:
    build:
      context: ..
      dockerfile: docker/samples/cpp/transformer.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}-develop"
    image: "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}-${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/samples/cpp/transformer:/home/docker/ament_ws/src/transformer
