version: "3.8"
services:
  # radar_object_detection:
  #   build:
  #     context: ..
  #     dockerfile: docker/perception/radar_object_detection.Dockerfile
  #     cache_from: 
  #       - "${RADAR_OBJECT_DETECTION_IMAGE:?}:${TAG}"
  #       - "${RADAR_OBJECT_DETECTION_IMAGE:?}:main"
  #   image: "${RADAR_OBJECT_DETECTION_IMAGE:?}:${TAG}"
  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ../src/perception/radar_object_detection:/home/docker/ament_ws/src/radar_object_detection
  camera_segmentation:
    build:
      context: ..
      dockerfile: docker/perception/camera_segmentation.Dockerfile
      cache_from: 
        - "${CAMERA_SEGMENTATION_IMAGE:?}:${TAG}"
        - "${CAMERA_SEGMENTATION_IMAGE:?}:main"
    image: "${CAMERA_SEGMENTATION_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/perception/camera_segmentation:/home/docker/ament_ws/src/camera_segmentation
      - /mnt/wato-drive2/perception-weights/semantic_segmentation:/home/docker/ament_ws/src/camera_segmentation/camera_segmentation/models
