version: "3.8"
services:
  carla_server_0:
    build:
      context: ..
      dockerfile: docker/carla_server/Dockerfile
      cache_from:
        - "${CARLA_SERVER_IMAGE:?}:latest"
      args:
        - CARLA_VERSION=0.9.13
    image: "${CARLA_SERVER_IMAGE:?}:latest"
    environment:
      - DISPLAY=1
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
    container_name: ${COMPOSE_PROJECT_NAME:?}_carla_0
    restart: always
    runtime: nvidia
    command: /bin/bash -c "./CarlaUE4.sh -nosound -carla-server -RenderOffscreen -world-port=2000"
    networks:
      - carla_instance_network_0

  carla_notebook_0:
    build:
      context: ..
      dockerfile: docker/simulation/carla_notebooks.Dockerfile
      args:
        - CARLA_VERSION=0.9.13
    image: python_api_test
    user: root:root
    environment:
      - CLIENT_NAME=${COMPOSE_PROJECT_NAME:?}_carla_0
      - VARIABLE=0.0
    container_name: ${COMPOSE_PROJECT_NAME:?}_carla_notebook_0
    # command: python3 ./logs/data_collection_mpc.py
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - carla_instance_network_0
    volumes:
      - ../src/simulation/carla_notebooks/logs:/root/carla_notebooks/logs
# LAST LINE GETS DELETED

networks:
  carla_instance_network_0: