version: "3.8"
services:
  aggregator: # C++
    build:
      context: ..
      dockerfile: docker/samples/cpp_aggregator.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:main"
    image: "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
    security_opt:
      - seccomp:${MODULES_DIR}/seccomp_profile.json 
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ${MONO_DIR}/src/samples/cpp/aggregator:/home/docker/ament_ws/src/aggregator

  # aggregator: # PYTHON
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/py_aggregator.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:main"
  #   image: "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:${TAG}"
  #   security_opt:
  #     - seccomp:${MODULES_DIR}/seccomp_profile.json 
  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ${MONO_DIR}/src/samples/python/aggregator:/home/docker/ament_ws/src/aggregator

  # producer: # C++
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/cpp_producer.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:main"
  #   image: "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
  #   security_opt:
  #     - seccomp:${MODULES_DIR}/seccomp_profile.json 
  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ${MONO_DIR}/src/samples/cpp/producer:/home/docker/ament_ws/src/producer

  producer: # PYTHON
    build:
      context: ..
      dockerfile: docker/samples/py_producer.Dockerfile
      cache_from:
        - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:${TAG}"
        - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:main"
    image: "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:${TAG}"
    security_opt:
      - seccomp:${MODULES_DIR}/seccomp_profile.json 
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ${MONO_DIR}/src/samples/python/producer:/home/docker/ament_ws/src/producer

  # transformer: # C++
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/cpp_transformer.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:main"
  #   image: "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
  #   security_opt:
  #     - seccomp:${MODULES_DIR}/seccomp_profile.json 
  #   user: ${FIXUID:?}:${FIXGID:?}
  #   volumes:
  #     - ${MONO_DIR}/src/samples/cpp/transformer:/home/docker/ament_ws/src/transformer

  transformer: # PYTHON
    build:
      context: ..
      dockerfile: docker/samples/python/py_transformer.Dockerfile
      cache_from:
        - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:${TAG}"
        - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:main"
    image: "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:${TAG}"
    security_opt:
      - seccomp:${MODULES_DIR}/seccomp_profile.json 
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ${MONO_DIR}/src/samples/python/transformer:/home/docker/ament_ws/src/transformer
