version: "3.8"
services:
  lidar_object_detection:
    build:
      context: ..
      dockerfile: docker/lidar_object_detection/lidar_object_detection.Dockerfile
      cache_from:
        - "${LIDAR_OBJECT_DETECTION_IMAGE:?}-${CACHE_FROM_TAG}"
        - "${LIDAR_OBJECT_DETECTION_IMAGE:?}-develop"
    image: "${LIDAR_OBJECT_DETECTION_IMAGE:?}-${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - ../src/lidar_object_detection:/home/docker/ament_ws/src/lidar_object_detection
