# Copyright (c) 2025-present WATonomous. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Launch file for preconfigured bag recording profiles.
# Usage: ros2 launch bag_recorder record.launch.yaml profile:=all_sensors
---
launch:
  - arg:
      name: "profile"
      default: "all_sensors"
      description: "Recording profile (all_sensors, camera_only, lidar_only)"

  - arg:
      name: "bag_path"
      default: "/bags"
      description: "Output directory for bag files"

  - node:
      pkg: rosbag2_transport
      exec: recorder
      name: bag_recorder
      output: screen
      param:
        - from: "$(find-pkg-share bag_recorder)/config/$(var profile).yaml"
        - name: "storage.uri"
          value: "$(var bag_path)"
