# Copyright (c) 2025-present WATonomous. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Oval track scenario - builds the oval as a real drivable world from OpenDRIVE."""

import os
import time

from carla_scenarios.scenario_base import ScenarioBase

try:
    import carla
except ImportError:
    carla = None


class OvalTrackScenario(ScenarioBase):
    """
    Generates the 4-lane oval track world from OpenDRIVE and puts the ego on it.

    Unlike the town scenarios, this does not load a shipped CARLA map: it feeds CARLA
    the OpenDRIVE emitted by tools/generate_oval_track.py, so the car drives on the
    same geometry that world_model loads as a lanelet map and that the fake_planner
    replays as a maneuver.

    Pair with (the rig comes up held in standby; release it with the start_trajectory service):
        ros2 launch fake_planner fake_planner_sim.launch.yaml maneuver:=oval_track
    """

    # Generated by tools/generate_oval_track.py; mounted into the container from maps/.
    XODR_PATH = "/opt/watonomous/maps/osm/oval_track_4_lane.xodr"

    # Start of the drive lane in OpenDRIVE coords -- must match the "start" pose in
    # fake_planner/maneuvers/oval_track.json. Y is negated below (CARLA is left-handed),
    # then snapped to the lane via the waypoint API for the exact centreline pose + heading.
    # Both come from DRIVE_LANE in tools/generate_oval_track.py (lane 1, the second lane in
    # from the inside): -Y is the lane centreline radius, 35.0 + (1 + 0.5) * 3.5.
    START_X = -42.0
    START_Y = -40.25

    SPAWN_Z_OFFSET = 0.5  # drop the car in slightly above the road

    def get_name(self) -> str:
        return "Oval Track"

    def get_description(self) -> str:
        return "4-lane oval track generated from OpenDRIVE, ego on the inner lane"

    def initialize(self, client: "carla.Client") -> bool:
        return self._initialize_carla(client)

    def _generate_track_world(self, wait_time: float = 5.0) -> bool:
        """Build the CARLA world from the generated OpenDRIVE file."""
        if not os.path.exists(self.XODR_PATH):
            self._log(
                f"OpenDRIVE not found at {self.XODR_PATH}. Generate it with "
                "`python3 tools/generate_oval_track.py` and make sure maps/ is mounted "
                "into this container.",
                "error",
            )
            return False

        with open(self.XODR_PATH, "r") as f:
            xodr = f.read()

        params = carla.OpendriveGenerationParameters(
            vertex_distance=2.0,
            max_road_length=100.0,
            wall_height=0.0,  # no barriers: the controller is what should keep us on track
            additional_width=1.0,  # small mesh margin so the outer lane edge isn't a cliff
            smooth_junctions=True,
            enable_mesh_visibility=True,
        )

        self._log(f"Generating oval track world from {self.XODR_PATH}...")
        self.client.generate_opendrive_world(xodr, params)
        time.sleep(wait_time)
        self.world = self.client.get_world()
        return True

    def setup(self) -> bool:
        if self.world is None:
            return False

        try:
            if not self._generate_track_world():
                return False

            carla_map = self.world.get_map()

            # OpenDRIVE -> CARLA: negate Y (CARLA is left-handed).
            target = carla.Location(x=self.START_X, y=-self.START_Y, z=0.0)
            waypoint = carla_map.get_waypoint(
                target, project_to_road=True, lane_type=carla.LaneType.Driving
            )
            if waypoint is None:
                self._log(
                    "No driving lane found near the track start - the OpenDRIVE world "
                    "did not generate drivable lanes.",
                    "error",
                )
                return False

            snapped = waypoint.transform.location
            drift = snapped.distance(target)
            self._log(
                f"Snapped ego start to lane {waypoint.lane_id} "
                f"({snapped.x:.2f}, {snapped.y:.2f}), {drift:.2f} m from the requested point"
            )
            if drift > 2.0:
                self._log(
                    f"Ego start snapped {drift:.2f} m away from the intended lane centreline; "
                    "the fake_planner maneuver may not line up with the road.",
                    "warn",
                )

            spawn_point = waypoint.transform
            spawn_point.location.z += self.SPAWN_Z_OFFSET
            if not self.spawn_ego_vehicle(spawn_point):
                return False

            self.world.set_weather(carla.WeatherParameters.ClearNoon)

            self._log(f"Setup complete: {self.get_name()}")
            return True

        except AttributeError as e:
            # generate_opendrive_world / OpendriveGenerationParameters are not present in
            # every CARLA build; make that failure legible rather than a bare traceback.
            self._log(
                f"This CARLA build appears not to support OpenDRIVE world generation: {e}",
                "error",
            )
            return False
        except Exception as e:
            self._log(f"Failed to setup: {e}", "error")
            return False
