# Copyright (c) 2025-present WATonomous. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Oval track scenario - builds the oval as a real drivable world from OpenDRIVE."""

import json
import os
import time

from carla_scenarios.scenario_base import ScenarioBase

try:
    import carla
except ImportError:
    carla = None


class OvalTrackScenario(ScenarioBase):
    """
    Generates the 4-lane oval track world from OpenDRIVE and puts the ego on it.

    Unlike the town scenarios this does not load a shipped CARLA map: it feeds CARLA the
    OpenDRIVE emitted by tools/generate_oval_track.py, so the car drives on the same geometry
    world_model loads as a lanelet map and the fake_planner replays as a maneuver.

    Pair with:
        ros2 launch fake_planner fake_planner_sim.launch.yaml maneuver:=oval_track
    """

    # Both generated by tools/generate_oval_track.py and mounted into the container from maps/.
    # The spawn sidecar carries the drive lane's start pose, so the ego is put down on exactly the
    # geometry fake_planner/maneuvers/oval_track.json replays -- the generator is the only place
    # that pose is written, rather than it being duplicated here and kept in step by hand.
    XODR_PATH = "/opt/watonomous/maps/osm/oval_track_4_lane.xodr"
    SPAWN_PATH = "/opt/watonomous/maps/osm/oval_track_spawn.json"

    SPAWN_Z_OFFSET = 0.5  # drop the car in slightly above the road

    # How far the CARLA waypoint API may snap the requested start before the maneuver and the road
    # have visibly parted company.
    MAX_SNAP_DRIFT_M = 2.0

    # Bounds on waiting for generate_opendrive_world to produce a drivable map.
    WORLD_READY_TIMEOUT_S = 30.0
    WORLD_POLL_INTERVAL_S = 0.5

    def get_name(self) -> str:
        return "Oval Track"

    def get_description(self) -> str:
        return "4-lane oval track generated from OpenDRIVE, ego on the inner lane"

    def initialize(self, client: "carla.Client") -> bool:
        return self._initialize_carla(client)

    def _read_spawn_pose(self):
        """The drive lane's start pose from the generator's sidecar, or None if unusable."""
        if not os.path.exists(self.SPAWN_PATH):
            self._log(
                f"Ego spawn pose not found at {self.SPAWN_PATH}. Generate it with "
                "`python3 tools/generate_oval_track.py` (it is written alongside the .xodr) "
                "and make sure maps/ is mounted into this container.",
                "error",
            )
            return None
        try:
            with open(self.SPAWN_PATH, "r") as f:
                spawn = json.load(f)
            return float(spawn["x"]), float(spawn["y"]), float(spawn["yaw"])
        except (ValueError, KeyError, TypeError, OSError) as e:
            self._log(
                f"Could not read the ego spawn pose from {self.SPAWN_PATH}: {e}",
                "error",
            )
            return None

    def _wait_for_drivable_world(self, target: "carla.Location"):
        """
        Poll until the generated world exposes a driving lane near `target`, and return that
        waypoint.

        generate_opendrive_world returns before the road mesh and lane graph are queryable, and how
        long that takes scales with the machine. Polling for the thing actually needed -- a driving
        waypoint at the start -- rather than sleeping a fixed interval means a slow host waits
        longer instead of failing with a misleading "no driving lane found".
        """
        deadline = time.monotonic() + self.WORLD_READY_TIMEOUT_S
        while True:
            try:
                self.world = self.client.get_world()
                waypoint = self.world.get_map().get_waypoint(
                    target, project_to_road=True, lane_type=carla.LaneType.Driving
                )
                if waypoint is not None:
                    return waypoint
            except RuntimeError:
                # The world is mid-swap; that is what we are waiting out.
                pass
            if time.monotonic() >= deadline:
                self._log(
                    f"No driving lane appeared near the track start within "
                    f"{self.WORLD_READY_TIMEOUT_S:.0f} s -- the OpenDRIVE world did not generate "
                    "drivable lanes.",
                    "error",
                )
                return None
            time.sleep(self.WORLD_POLL_INTERVAL_S)

    def _generate_track_world(self) -> bool:
        """Feed CARLA the generated OpenDRIVE file."""
        if not os.path.exists(self.XODR_PATH):
            self._log(
                f"OpenDRIVE not found at {self.XODR_PATH}. Generate it with "
                "`python3 tools/generate_oval_track.py` and make sure maps/ is mounted "
                "into this container.",
                "error",
            )
            return False

        with open(self.XODR_PATH, "r") as f:
            xodr = f.read()

        params = carla.OpendriveGenerationParameters(
            vertex_distance=2.0,
            max_road_length=100.0,
            wall_height=0.0,  # no barriers: the controller is what should keep us on track
            additional_width=1.0,  # small mesh margin so the outer lane edge isn't a cliff
            smooth_junctions=True,
            enable_mesh_visibility=True,
        )

        self._log(f"Generating oval track world from {self.XODR_PATH}...")
        self.client.generate_opendrive_world(xodr, params)
        return True

    def setup(self) -> bool:
        if self.world is None:
            return False

        try:
            spawn_pose = self._read_spawn_pose()
            if spawn_pose is None:
                return False
            start_x, start_y, _start_yaw = spawn_pose

            if not self._generate_track_world():
                return False

            # OpenDRIVE -> CARLA: negate Y (CARLA is left-handed).
            target = carla.Location(x=start_x, y=-start_y, z=0.0)
            waypoint = self._wait_for_drivable_world(target)
            if waypoint is None:
                return False

            snapped = waypoint.transform.location
            drift = snapped.distance(target)
            self._log(
                f"Snapped ego start to lane {waypoint.lane_id} "
                f"({snapped.x:.2f}, {snapped.y:.2f}), {drift:.2f} m from the requested point"
            )
            if drift > self.MAX_SNAP_DRIFT_M:
                self._log(
                    f"Ego start snapped {drift:.2f} m away from the intended lane centreline; "
                    "the fake_planner maneuver may not line up with the road.",
                    "warn",
                )

            spawn_point = waypoint.transform
            spawn_point.location.z += self.SPAWN_Z_OFFSET
            if not self.spawn_ego_vehicle(spawn_point):
                return False

            self.world.set_weather(carla.WeatherParameters.ClearNoon)

            self._log(f"Setup complete: {self.get_name()}")
            return True

        except AttributeError as e:
            # generate_opendrive_world / OpendriveGenerationParameters are missing in some
            # CARLA builds; make that failure legible rather than a bare traceback.
            self._log(
                f"This CARLA build appears not to support OpenDRIVE world generation: {e}",
                "error",
            )
            return False
        except Exception as e:
            self._log(f"Failed to setup: {e}", "error")
            return False
