---
services:
  action_bringup:
    build:
      target: build
    extends:
      file: ../docker-compose.action.yaml
      service: action_bringup
    image: "${ACTION_IMAGE}:build_${TAG}"
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action:/home/bolty/ament_ws/src/action
