version: "3.8"

x-fixuid: &fixuid
  user: ${FIXUID:?}:${FIXGID:?}
  entrypoint: |
    /bin/bash -c "USER=docker && \
      GROUP=docker && \                                                                     
      curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4/fixuid-0.4-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \                                                                                                            
      chown root:root /usr/local/bin/fixuid && \                                                                              
      chmod 4755 /usr/local/bin/fixuid && \
      mkdir -p /etc/fixuid && \                                                                                               
      printf "user: $USER\ngroup: $GROUP\npaths:\n  - /home/docker/ \n  - /tmp/" > /etc/fixuid/config.yml && \
      /usr/local/bin/fixuid && \
      /home/docker/wato_ros_entrypoint.sh"

services:
  cpp_aggregator:
    <<: *fixuid
    extends:
      file: ../docker-compose.samples.yaml
      service: cpp_aggregator
    volumes:
      - ${MONO_DIR}/src/samples/cpp/aggregator:/home/docker/ament_ws/src/aggregator

  # py_aggregator: # PYTHON
  #   <<: *fixuid
  #   extends:
  #     file: ../docker-compose.samples.yaml
  #     service: py_aggregator
  #   volumes:
  #     - ${MONO_DIR}/src/samples/python/aggregator:/home/docker/ament_ws/src/aggregator

  # cpp_producer: # C++
  #   <<: *fixuid
  #   extends:
  #     file: ../docker-compose.samples.yaml
  #     service: cpp_producer
  #   volumes:
  #     - ${MONO_DIR}/src/samples/cpp/producer:/home/docker/ament_ws/src/producer

  py_producer: # PYTHON
    <<: *fixuid
    extends:
      file: ../docker-compose.samples.yaml
      service: py_producer
    volumes:
      - ${MONO_DIR}/src/samples/python/producer:/home/docker/ament_ws/src/producer

  # cpp_transformer: # C++
  #   <<: *fixuid
  #   extends:
  #     file: ../docker-compose.samples.yaml
  #     service: cpp_transformer
  #   volumes:
  #     - ${MONO_DIR}/src/samples/cpp/transformer:/home/docker/ament_ws/src/transformer

  py_transformer: # PYTHON
    <<: *fixuid
    extends:
      file: ../docker-compose.samples.yaml
      service: py_transformer
    volumes:
      - ${MONO_DIR}/src/samples/python/transformer:/home/docker/ament_ws/src/transformer
