version: "3.8"

x-fixuid: &fixuid
  build:
    target: build

services:
  global_planning:
    <<: *fixuid
    extends:
      file: ../docker-compose.action.yaml
      service: global_planning
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/global_planning:/home/ament_ws/src/global_planning

  behaviour_planning:
    <<: *fixuid
    extends:
      file: ../docker-compose.action.yaml
      service: behaviour_planning
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/behaviour_planning:/home/ament_ws/src/behaviour_planning

  local_planning:
    <<: *fixuid
    extends:
      file: ../docker-compose.action.yaml
      service: local_planning
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/local_planning:/home/ament_ws/src/local_planning

  model_predictive_control:
    <<: *fixuid
    extends:
      file: ../docker-compose.action.yaml
      service: model_predictive_control
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/model_predictive_control:/home/ament_ws/src/model_predictive_control