version: "3.8"

x-fixuid: &fixuid
  build:
    target: build

services:
  global_planning:
    <<: *fixuid
    extends:
      file: ../docker-compose.action.yaml
      service: global_planning
    image: "${ACTION_GLOBAL_PLANNING_IMAGE}:build_${TAG}"
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/global_planning:/home/bolty/ament_ws/src/global_planning

  behaviour_planning:
    <<: *fixuid
    extends:
      file: ../docker-compose.action.yaml
      service: behaviour_planning
    image: "${ACTION_BEHAVIOUR_PLANNING_IMAGE}:build_${TAG}"
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/behaviour_planning:/home/bolty/ament_ws/src/behaviour_planning

  local_planning:
    <<: *fixuid
    extends:
      file: ../docker-compose.action.yaml
      service: local_planning
    image: "${ACTION_LOCAL_PLANNING_IMAGE}:build_${TAG}"
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/local_planning:/home/bolty/ament_ws/src/local_planning

  model_predictive_control:
    extends:
      file: ../docker-compose.action.yaml
      service: model_predictive_control
    image: "${ACTION_MPC_IMAGE}:build_${TAG}"
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/model_predictive_control:/home/bolty/ament_ws/src/model_predictive_control

  pure_pursuit_control:
    extends:
      file: ../docker-compose.action.yaml
      service: pure_pursuit_control
    image: "${ACTION_PURE_PURSUIT_IMAGE}:build_${TAG}"
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/pure_pursuit_control:/home/bolty/ament_ws/src/pure_pursuit_control

  behaviour_tree:
    extends:
      file: ../docker-compose.action.yaml
      service: behaviour_tree
    image: "${ACTION_BEHAVIOUR_TREE_IMAGE}:build_${TAG}"
    command: tail -F anything
    volumes:
      - ${MONO_DIR}/src/action/behaviour_tree:/home/bolty/ament_ws/src/behaviour_tree