camera_object_detection_node:
  ros__parameters:
    camera_info_topic: /CAM_FRONT/camera_info
    lidar_topic: /LIDAR_TOP
    detections_topic: /detections

    publish_detections_topic: /detections_3d
    publish_markers_topic: /markers_3d
    publish_clusters_topic: /clustered_pc
    
    camera_frame: CAM_FRONT
    lidar_frame: LIDAR_TOP

    clustering_distances: [5., 30., 45., 60.]
    clustering_thresholds: [0.5, 1.1, 1.6, 2.1, 2.6]
    cluster_size_min: 20.
    cluster_size_max: 100000.
    cluster_merge_threshold: 1.5
