map_server:
  ros__parameters:
    yaml_filename: "/map/map.yaml"
    frame_id: "map"
    use_sim_time: false
    autostart: true
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: ["scan"]
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.7

amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    kld_err: 0.02
    kld_z: 0.99
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 0.1
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    scan_topic: "scan"
    robot_model_type: "differential"
    motion_model_type: "nav2_amcl::DifferentialMotionModel"
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0