---
/**:
  ros__parameters:
    use_sim_time: true # only for ROS bags or simulation
    sensor_timeout: 1.0

wheel_odometry:
  ros__parameters:
    wheel_odometry_output_topic: "/localization/odometry/wheel_odometry"
    vehicle_status_topic: "/vehicle_status"
    wheel_base: 2.875               # distance between front and rear axles

ekf_filter_node_local:
  ros__parameters:
    frequency: 15.0                 # EKF update rate
    two_d_mode: true                # ignore Z axis for 2D robot
    odom_frame: odom                # local odometry frame
    base_link_frame: base_link      # robot frame
    world_frame: odom               # output frame (local pose)
    publish_tf: true                # broadcast odom -> base_link TF
    # debug: true

    # Odometry data (from wheel odometry)
    odom0: /localization/odometry/wheel_odometry
    odom0_config: [
      false, false, false,   # x, y, z positions (we don’t trust wheel odom for position)
      false, false, false,   # roll, pitch, yaw angles
      true, true, false,     # vx, vy, vz (linear velocities)
      false, false, true,    # vroll, vpitch, vyaw (angular velocities)
      false, false, false    # ax, ay, az (linear accelerations)
    ]

    # IMU data for orientation
    imu0: /imu
    imu0_config: [
      false, false, false,
      false, false, true,
      false, false, false,
      false, false, true,
      true, false, false
    ]

ekf_filter_node_global:
  ros__parameters:
    frequency: 15.0                  # EKF update rate
    two_d_mode: true                # ignore Z axis for 2D robot
    odom_frame: odom                # local odometry frame
    base_link_frame: base_link      # robot frame
    world_frame: map                # output frame
    publish_tf: true                # broadcast map -> base_link TF
    # transform_time_offset: 1.0      # prevents error in navsat_transform
    initial_state: [
      73.6, -66.4, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0
    ] # the initial state. Note: the numbers here are for CARLA (change for real car)

    # Odometry data (from wheel odometry)
    odom0: /localization/odometry/wheel_odometry
    odom0_config: [
      false, false, false,   # x, y, z positions (we don’t trust wheel odom for position)
      false, false, false,   # roll, pitch, yaw angles
      true, true, false,     # vx, vy, vz (linear velocities)
      false, false, true,    # vroll, vpitch, vyaw (angular velocities)
      false, false, false    # ax, ay, az (linear accelerations)
    ]

    # Odometry data (from navsat_transform)
    odom1: /localization/odometry/gps
    odom1_config: [
      true, true, false,
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, false
    ]

    # IMU data for orientation
    imu0: /imu
    imu0_config: [
      false, false, false,
      false, false, true,
      false, false, false,
      false, false, true,
      true, false, false
    ]

navsat_transform:
  ros__parameters:
    frequency: 10.0
    # delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0 # 1.5707963 # 90 degrees in radians
    zero_altitude: true
    broadcast_cartesian_transform: false
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false
