odom:
  ros__parameters: 
    odom_output_topic: "/bicycle_model_output"
    wheel_base: 2.65
    odom_publish_rate: 10
odom_mock_data:
  ros__parameters: 
    right_wheel_topic: "/motor_encoder_right"
    left_wheel_topic: "/motor_encoder_left"
    steering_topic: "/steering_angle"
    wheel_speed_min: 3.0
    wheel_speed_max: 3.0
    turning_angle_min: 0.0
    turning_angle_max: 0.0
    wheel_publish_rate: 1000
    turn_publish_rate: 1000

