name: Check Monorepo Code Styling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters-python:
    name: Run Python linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black autopep8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          Autopep8: true

  run-linters-cpp:
    name: Run C++ linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true