---
name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-pre-commit:
    name: Pre-commit Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install xmllint dependency
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libxml2-utils

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
